default_platform(:android)
platform :android do
  desc "Distribute app to firebase app distribution"
  lane :Distribute do
    require 'dotenv'
    Dotenv.load(File.expand_path('../../.env', __dir__))
    sh "flutter clean"
    sh "flutter build apk --release"
    firebase_app_distribution(
    app: ENV['FIREBASE_APP_ID'],
    firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
    testers: "mmaatt712@gmail.com",
    release_notes: "A new version of the app has been released. Please update to the latest version."
  )
  end
end